<?php
// Google reCAPTCHA v2
define('RECAPTCHA_SITE_KEY',   getenv('RECAPTCHA_SITE_KEY')   ?: '6LdUs-csAAAAAO0OwhwPWMTV941Vs7jN3XWB7MhT');
define('RECAPTCHA_SECRET_KEY', getenv('RECAPTCHA_SECRET_KEY') ?: '6LdUs-csAAAAAC1ezjVMiAAUtS0GWoQrvYSsITCo');